# Generated by Django 2.2.2 on 2019-09-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190822_0933'),
        ('news', '0005_auto_20190831_1928'),
    ]

    operations = [
    ]
